server.port=8081

#spring.datasource.url=jdbc:mysql://mysql-295fedeb-rntsang-b251.a.aivencloud.com:13336/\
#tax_bracket?ssl-mode=REQUIRED&verifyServerCertificate=true&\
#useSSL=true&requireSSL=true&\
#trustCertificateKeyStoreUrl=file:C:/example/demo/src/main/resources/truststore.jks&\
#trustCertificateKeyStorePassword=password
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_UsUv6bunUOFlLiO5k0B
#
#hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://mysql-295fedeb-rntsang-b251.a.aivencloud.com:13336/TaxOptimizer
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_UsUv6bunUOFlLiO5k0B
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver