theme: jekyll-theme-primer
title: Nest Egg Optimizer
description: Retirement Portfolio Withdrawal Optimizer & Simulator Documentation
show_downloads: false
google_analytics:
# Add any other Jekyll configuration variables here if needed
